info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: show app info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show home
swagger: "2.0"
